#![cfg(target_os = "linux")]

//! Opt-in integration tests. Run with `--ignored --test-threads=1` on a Linux
//! host with Vivado installed. The harness never shares the server workspace.

use nix::libc;
use reqwest::{Client, Method, RequestBuilder, StatusCode};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use std::{
    fs,
    future::Future,
    io,
    os::fd::{AsRawFd, FromRawFd, OwnedFd},
    path::PathBuf,
    sync::{Arc, Mutex},
    time::Duration,
};
use tempfile::TempDir;
use tokio::{
    task::JoinHandle,
    time::{self, Instant},
};
use uuid::Uuid;
use vivado_server::{AppConfig, AppRuntime};

const TOKEN: &str = "0123456789abcdef0123456789abcdef";
const RESULT: &[u8] = b"generated by real Vivado\n";
const SCRIPT: &[u8] = br#"set output [open result.txt w]
fconfigure $output -translation lf -encoding utf-8
puts $output {generated by real Vivado}
close $output
puts {}
puts {__ARTIFACT_READY__}
flush stdout
"#;

fn startup_timeout() -> Duration {
    let seconds = match std::env::var("VIVADO_TEST_STARTUP_TIMEOUT_SECS") {
        Ok(value) => value
            .parse::<u64>()
            .expect("VIVADO_TEST_STARTUP_TIMEOUT_SECS must be an integer"),
        Err(std::env::VarError::NotPresent) => 120,
        Err(error) => panic!("invalid VIVADO_TEST_STARTUP_TIMEOUT_SECS: {error}"),
    };
    assert!(
        (1..=3600).contains(&seconds),
        "VIVADO_TEST_STARTUP_TIMEOUT_SECS must be between 1 and 3600"
    );
    Duration::from_secs(seconds)
}

fn sha256(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

// A numeric PID is insufficient for either an assertion or emergency cleanup:
// /proc starttime detects reuse and pidfds make signalling race-free.
#[derive(Clone, Debug)]
struct ProcessIdentity {
    pid: i32,
    parent: i32,
    group: i32,
    started: u64,
    live: bool,
}

fn process_identity(pid: i32) -> io::Result<Option<ProcessIdentity>> {
    let bytes = match fs::read(format!("/proc/{pid}/stat")) {
        Ok(bytes) => bytes,
        Err(error)
            if error.kind() == io::ErrorKind::NotFound
                || error.raw_os_error() == Some(libc::ESRCH) =>
        {
            return Ok(None);
        }
        Err(error) => return Err(error),
    };
    let invalid = || io::Error::other("invalid /proc process stat");
    let end = bytes
        .iter()
        .rposition(|byte| *byte == b')')
        .ok_or_else(invalid)?;
    let text = std::str::from_utf8(&bytes[end + 1..]).map_err(|_| invalid())?;
    let fields: Vec<_> = text.split_ascii_whitespace().collect();
    let parse = |index: usize| -> io::Result<u64> {
        fields
            .get(index)
            .ok_or_else(invalid)?
            .parse()
            .map_err(|_| invalid())
    };
    let state = *fields.first().ok_or_else(invalid)?;
    Ok(Some(ProcessIdentity {
        pid,
        parent: i32::try_from(parse(1)?).map_err(|_| invalid())?,
        group: i32::try_from(parse(2)?).map_err(|_| invalid())?,
        started: parse(19)?,
        // An unreaped single-thread zombie cannot execute or retain open FDs.
        live: !matches!(state, "Z" | "X" | "x") || parse(17)? > 1,
    }))
}

struct TrackedProcess {
    identity: ProcessIdentity,
    fd: OwnedFd,
}

impl TrackedProcess {
    fn attach(identity: ProcessIdentity) -> io::Result<Option<Self>> {
        let descriptor = unsafe { libc::syscall(libc::SYS_pidfd_open, identity.pid, 0) };
        if descriptor < 0 {
            let error = io::Error::last_os_error();
            if error.raw_os_error() == Some(libc::ESRCH) {
                return Ok(None);
            }
            return Err(error);
        }
        let fd = unsafe { OwnedFd::from_raw_fd(descriptor as i32) };
        if process_identity(identity.pid)?.is_none_or(|current| current.started != identity.started)
        {
            return Ok(None);
        }
        Ok(Some(Self { identity, fd }))
    }

    fn is_alive(&self) -> io::Result<bool> {
        Ok(process_identity(self.identity.pid)?
            .is_some_and(|current| current.started == self.identity.started && current.live))
    }

    fn kill(&self) -> io::Result<()> {
        let result = unsafe {
            libc::syscall(
                libc::SYS_pidfd_send_signal,
                self.fd.as_raw_fd(),
                libc::SIGKILL,
                std::ptr::null::<libc::siginfo_t>(),
                0,
            )
        };
        if result >= 0 {
            return Ok(());
        }
        let error = io::Error::last_os_error();
        if error.raw_os_error() == Some(libc::ESRCH) {
            Ok(())
        } else {
            Err(error)
        }
    }
}

struct RealServer {
    base: String,
    workspace: TempDir,
    runtime: Arc<AppRuntime>,
    client: Client,
    http: JoinHandle<()>,
    processes: Mutex<Vec<TrackedProcess>>,
    startup: Duration,
}

impl RealServer {
    async fn spawn() -> Self {
        let startup = startup_timeout();
        // Check the optional test harness requirement before starting any child.
        let own_identity = process_identity(std::process::id() as i32)
            .unwrap()
            .expect("the current test process must exist in /proc");
        assert!(
            TrackedProcess::attach(own_identity)
                .expect("real tests require Linux pidfd support (kernel 5.3 or newer)")
                .is_some()
        );
        let vivado_path = PathBuf::from(
            std::env::var_os("VIVADO_PATH")
                .expect("set VIVADO_PATH to an executable Linux Vivado launcher"),
        );
        let workspace = match std::env::var_os("VIVADO_TEST_WORKSPACE_ROOT") {
            Some(root) => tempfile::tempdir_in(root)
                .expect("VIVADO_TEST_WORKSPACE_ROOT must be an existing writable directory"),
            None => tempfile::tempdir().unwrap(),
        };
        let config = AppConfig {
            listen_addr: "127.0.0.1:0".into(),
            vivado_path,
            workspace_root: workspace.path().to_owned(),
            auth_tokens: vec![TOKEN.into()],
            allow_run_as_root: true,
            output_buffer_bytes: 4 * 1024 * 1024,
            // Readiness polling does not renew a workflow heartbeat. Slow licensed
            // startup must not expire the workflow before the startup deadline.
            heartbeat_timeout_secs: startup.as_secs() * 2 + 300,
            sync_max_file_bytes: 16 * 1024 * 1024,
            shutdown_grace_secs: 15,
            ..AppConfig::default()
        };
        let runtime = Arc::new(AppRuntime::initialize(config).await.unwrap());
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let app = runtime.router();
        let http = tokio::spawn(async move {
            axum::serve(listener, app).await.unwrap();
        });
        Self {
            base: format!("http://{address}"),
            workspace,
            runtime,
            http,
            startup,
            client: Client::builder()
                .timeout(Duration::from_secs(30))
                .build()
                .unwrap(),
            processes: Mutex::new(Vec::new()),
        }
    }

    fn request(&self, method: Method, id: Uuid, suffix: &str) -> RequestBuilder {
        self.client
            .request(method, format!("{}/v1/workflows/{id}{suffix}", self.base))
            .bearer_auth(TOKEN)
    }

    async fn json(&self, request: RequestBuilder) -> Value {
        let response = request.send().await.unwrap();
        let status = response.status();
        let body = response.text().await.unwrap();
        assert!(status.is_success(), "HTTP {status}: {body}");
        serde_json::from_str(&body).expect("expected a JSON response")
    }

    async fn create(&self, project: &str) -> Uuid {
        let id = Uuid::new_v4();
        let response = self
            .json(
                self.request(Method::PUT, id, "")
                    .json(&json!({"project": project, "reset_project": true})),
            )
            .await;
        assert_eq!(response["status"], "preparing");
        assert_eq!(response["requires_full_upload"], true);
        id
    }

    async fn upload_script(&self, id: Uuid) {
        let plan = self.json(self.request(Method::POST, id, "/sync/push/plan")
            .json(&json!({"entries": [{"path": "smoke.tcl", "kind": "file", "size_bytes": SCRIPT.len(),
                "mtime_unix_ms": 1_700_000_000_000_i64, "sha256": sha256(SCRIPT), "executable": false}]}))).await;
        assert_eq!(plan["upload_files"].as_array().unwrap().len(), 1);
        assert_eq!(plan["upload_files"][0]["path"], "smoke.tcl");
        let sync = plan["sync_id"].as_str().unwrap();
        let uploaded = self
            .json(
                self.request(Method::PUT, id, &format!("/sync/{sync}/files/smoke.tcl"))
                    .body(SCRIPT.to_vec()),
            )
            .await;
        assert_eq!(uploaded["size_bytes"], SCRIPT.len());
        assert_eq!(uploaded["sha256"], sha256(SCRIPT));
        let committed = self
            .json(
                self.request(Method::POST, id, &format!("/sync/{sync}/commit"))
                    .json(&json!({})),
            )
            .await;
        assert_eq!(committed["status"], "committed");
    }

    async fn input(&self, id: Uuid, text: &str) {
        self.json(
            self.request(Method::POST, id, "/session/stdin")
                .json(&json!({"text": text})),
        )
        .await;
    }

    async fn output_until(&self, id: Uuid, needle: &str, timeout: Duration) -> String {
        let deadline = Instant::now() + timeout;
        let mut cursor = 0;
        let mut output = String::new();
        loop {
            let response = self
                .json(self.request(
                    Method::GET,
                    id,
                    &format!("/session/output?cursor={cursor}&timeout_ms=1000"),
                ))
                .await;
            assert_eq!(
                response["overrun"], false,
                "output cursor overrun: {response}"
            );
            assert_eq!(
                response["output_truncated"], false,
                "output truncated: {response}"
            );
            cursor = response["cursor"].as_u64().unwrap();
            for chunk in response["chunks"].as_array().unwrap() {
                output.push_str(chunk["text"].as_str().unwrap());
            }
            // PTY reads can split a marker's value; wait for its complete line.
            let found = match needle.strip_prefix('\n') {
                Some(prefix) => output
                    .split_inclusive('\n')
                    .any(|line| line.ends_with('\n') && line.trim_start().starts_with(prefix)),
                None => output.contains(needle),
            };
            if found {
                return output;
            }
            assert_eq!(
                response["status"], "running",
                "Vivado exited before {needle:?}: {output}"
            );
            assert!(
                Instant::now() < deadline,
                "timed out waiting for {needle:?}: {output}"
            );
        }
    }

    async fn wait_status(&self, id: Uuid, suffix: &str, expected: &str) -> Value {
        let deadline = Instant::now() + Duration::from_secs(30);
        loop {
            let info = self.json(self.request(Method::GET, id, suffix)).await;
            if info["status"] == expected {
                return info;
            }
            assert!(Instant::now() < deadline, "expected {expected}: {info}");
            time::sleep(Duration::from_millis(50)).await;
        }
    }

    fn track(&self, identity: ProcessIdentity) -> io::Result<()> {
        let mut tracked = self
            .processes
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        if tracked.iter().any(|process| {
            process.identity.pid == identity.pid && process.identity.started == identity.started
        }) {
            return Ok(());
        }
        if let Some(process) = TrackedProcess::attach(identity)? {
            tracked.push(process);
        }
        Ok(())
    }

    fn track_pid(&self, pid: i32) -> ProcessIdentity {
        assert!(pid > 1);
        let identity = process_identity(pid)
            .unwrap()
            .expect("reported Vivado PID must exist");
        assert!(identity.live, "reported PID is not alive: {identity:?}");
        self.track(identity.clone())
            .expect("real tests require Linux pidfd support (kernel 5.3 or newer)");
        identity
    }

    fn capture_workspace_processes(&self) -> io::Result<()> {
        let root = self.workspace.path().canonicalize()?;
        let mut current = Vec::new();
        for entry in fs::read_dir("/proc")? {
            let entry = entry?;
            let Some(pid) = entry
                .file_name()
                .to_str()
                .and_then(|name| name.parse::<i32>().ok())
            else {
                continue;
            };
            if let Some(identity) = process_identity(pid)? {
                current.push(identity);
            }
        }
        // The launcher is a direct child in the unique temporary workspace.
        // Snapshot before shutdown as well, covering failure before Tcl emits a PID.
        let mut groups: Vec<_> = current
            .iter()
            .filter(|identity| {
                identity.parent == std::process::id() as i32
                    && identity.group == identity.pid
                    && fs::read_link(format!("/proc/{}/cwd", identity.pid))
                        .is_ok_and(|cwd| cwd.starts_with(&root))
            })
            .map(|identity| identity.group)
            .collect();
        // A launcher can already be a zombie with an unreadable cwd while its
        // descendants are still alive. Previously pinned identities also establish
        // ownership of a group without guessing from a reusable numeric PGID.
        {
            let tracked = self
                .processes
                .lock()
                .unwrap_or_else(|error| error.into_inner());
            for process in tracked.iter() {
                if let Some(identity) = current.iter().find(|identity| {
                    identity.pid == process.identity.pid
                        && identity.started == process.identity.started
                }) {
                    groups.push(identity.group);
                }
            }
        }
        for identity in current
            .into_iter()
            .filter(|identity| groups.contains(&identity.group))
        {
            self.track(identity)?;
        }
        Ok(())
    }

    async fn start(&self, id: Uuid) -> ProcessIdentity {
        self.json(
            self.request(Method::POST, id, "/session")
                .json(&json!({"args": ["-nolog", "-nojournal"]})),
        )
        .await;
        self.capture_workspace_processes().unwrap();
        self.output_until(id, "Vivado%", self.startup).await;
        // Raw PTY input does not echo a newline after the prompt. Start marker
        // output with an explicit newline and emit both values in one Tcl command.
        self.input(id, "puts {}; puts [format {__VIVADO_PID__%d} [pid]]; puts [format {__VIVADO_VERSION__%s} [version -short]]; flush stdout\n").await;
        let output = self
            .output_until(id, "\n__VIVADO_VERSION__", Duration::from_secs(30))
            .await;
        let version = marker(&output, "__VIVADO_VERSION__");
        assert!(!version.is_empty(), "missing Vivado version: {output}");
        if let Some(expected) = std::env::var_os("VIVADO_TEST_EXPECTED_VERSION") {
            let expected = expected
                .to_str()
                .expect("VIVADO_TEST_EXPECTED_VERSION must be UTF-8");
            assert!(
                !expected.is_empty(),
                "VIVADO_TEST_EXPECTED_VERSION must not be empty"
            );
            assert_eq!(version, expected, "unexpected Vivado version");
        }
        eprintln!("real Vivado version: {version}");
        self.track_pid(marker(&output, "__VIVADO_PID__").parse().unwrap())
    }

    async fn spawn_descendant(&self, id: Uuid, vivado: &ProcessIdentity) -> ProcessIdentity {
        self.input(id, "set child [exec /bin/sleep 600 &]; puts {}; puts [format {__VIVADO_CHILD_PID__%s} $child]; flush stdout; after 600000\n").await;
        let output = self
            .output_until(id, "\n__VIVADO_CHILD_PID__", Duration::from_secs(30))
            .await;
        let child = self.track_pid(marker(&output, "__VIVADO_CHILD_PID__").parse().unwrap());
        assert_eq!(
            child.parent, vivado.pid,
            "sleep must be a real Vivado child"
        );
        assert_eq!(
            child.group, vivado.group,
            "child must remain in the supported process group"
        );
        child
    }

    async fn wait_dead(&self, identities: &[ProcessIdentity]) {
        let deadline = Instant::now() + Duration::from_secs(10);
        loop {
            let alive: Vec<_> = identities
                .iter()
                .filter(|identity| {
                    process_identity(identity.pid)
                        .unwrap()
                        .is_some_and(|current| current.started == identity.started && current.live)
                })
                .collect();
            if alive.is_empty() {
                return;
            }
            assert!(
                Instant::now() < deadline,
                "processes survived cleanup: {alive:?}"
            );
            time::sleep(Duration::from_millis(50)).await;
        }
    }

    async fn complete(&self, id: Uuid, vivado: &ProcessIdentity) {
        self.input(id, "source smoke.tcl\n").await;
        self.output_until(id, "\n__ARTIFACT_READY__", Duration::from_secs(30))
            .await;
        self.input(id, "exit 0\n").await;
        let session = self.wait_status(id, "/session", "exited").await;
        assert_eq!(session["termination_reason"], "process_exited");
        assert_eq!(session["exit_code"], 0);
        self.wait_dead(std::slice::from_ref(vivado)).await;
        self.wait_status(id, "", "pulling").await;
        let plan = self
            .json(
                self.request(Method::POST, id, "/sync/pull/plan")
                    .json(&json!({"entries": []})),
            )
            .await;
        let mut found_result = false;
        for transfer in plan["download_files"].as_array().unwrap() {
            let path = transfer["path"].as_str().unwrap();
            let digest = transfer["sha256"].as_str().unwrap();
            let etag = format!("\"sha256:{digest}\"");
            let mut url =
                reqwest::Url::parse(&format!("{}/v1/workflows/{id}/sync/files/", self.base))
                    .unwrap();
            url.path_segments_mut()
                .unwrap()
                .pop_if_empty()
                .extend(path.split('/'));
            let response = self
                .client
                .get(url)
                .bearer_auth(TOKEN)
                .header(reqwest::header::IF_MATCH, &etag)
                .send()
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::OK, "download {path}");
            assert_eq!(response.headers()[reqwest::header::ETAG], etag);
            let bytes = response.bytes().await.unwrap();
            // The stream is not an immutable server snapshot. A client must check
            // the completed body against the plan before accepting any download.
            assert_eq!(
                bytes.len() as u64,
                transfer["size_bytes"].as_u64().unwrap(),
                "{path}"
            );
            assert_eq!(sha256(&bytes), digest, "{path}");
            if path == "result.txt" {
                assert_eq!(&bytes[..], RESULT);
                found_result = true;
            }
        }
        assert!(
            found_result,
            "Vivado-generated artifact missing from pull plan: {plan}"
        );
        let completed = self
            .json(self.request(Method::POST, id, "/finish").json(&json!({})))
            .await;
        assert_eq!(completed["status"], "completed");
    }
}

impl Drop for RealServer {
    fn drop(&mut self) {
        self.http.abort();
        for process in self
            .processes
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .iter()
        {
            let _ = process.kill();
        }
    }
}

fn marker<'a>(output: &'a str, prefix: &str) -> &'a str {
    output
        .lines()
        .find_map(|line| line.trim().strip_prefix(prefix))
        .unwrap_or_else(|| panic!("missing {prefix}: {output}"))
}

async fn run_scenario<F, Fut>(scenario: F)
where
    F: FnOnce(Arc<RealServer>) -> Fut + Send + 'static,
    Fut: Future<Output = ()> + Send + 'static,
{
    let server = Arc::new(RealServer::spawn().await);
    let copy = server.clone();
    let mut task = tokio::spawn(async move { scenario(copy).await });
    // Joining a separate task catches assertion panics while keeping the Tokio
    // runtime alive long enough to stop Vivado and remove the temporary workspace.
    let result = time::timeout(server.startup * 2 + Duration::from_secs(240), &mut task).await;
    if result.is_err() {
        task.abort();
        let _ = task.await;
    }
    let captured = server.capture_workspace_processes();
    let shutdown = time::timeout(Duration::from_secs(45), server.runtime.shutdown()).await;
    let mut survivors = Vec::new();
    let mut cleanup_errors = Vec::new();
    {
        let processes = server
            .processes
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        for process in processes.iter() {
            match process.is_alive() {
                Ok(false) => continue,
                Ok(true) => survivors.push(process.identity.clone()),
                Err(error) => cleanup_errors.push(error.to_string()),
            }
            if let Err(error) = process.kill() {
                cleanup_errors.push(error.to_string());
            }
        }
    }
    // Fallback cleanup must not turn a broken server shutdown into a passing test.
    if !survivors.is_empty() {
        server.wait_dead(&survivors).await;
    }
    if let Ok(Err(error)) = result {
        eprintln!(
            "cleanup after test failure: capture={captured:?}, shutdown={shutdown:?}, survivors={survivors:?}, errors={cleanup_errors:?}"
        );
        if error.is_panic() {
            std::panic::resume_unwind(error.into_panic());
        }
        panic!("real Vivado test task failed: {error}");
    }
    assert!(
        result.is_ok(),
        "real Vivado test exceeded its overall deadline"
    );
    captured.expect("could not capture test processes for cleanup");
    shutdown.expect("runtime shutdown exceeded 45 seconds");
    assert!(
        survivors.is_empty(),
        "runtime shutdown left live processes: {survivors:?}"
    );
    assert!(
        cleanup_errors.is_empty(),
        "emergency cleanup errors: {cleanup_errors:?}"
    );
}

#[tokio::test]
#[ignore = "requires Linux Vivado and pidfds; set VIVADO_PATH"]
async fn real_vivado_upload_tcl_exit_pull_finish() {
    run_scenario(|server| async move {
        let id = server.create("smoke").await;
        server.upload_script(id).await;
        let vivado = server.start(id).await;
        server.complete(id, &vivado).await;
    })
    .await;
}

#[tokio::test]
#[ignore = "requires Linux Vivado and pidfds; set VIVADO_PATH"]
async fn real_vivado_forced_tree_termination_requires_reset() {
    run_scenario(|server| async move {
        let id = server.create("forced").await;
        server.upload_script(id).await;
        let vivado = server.start(id).await;
        let child = server.spawn_descendant(id, &vivado).await;
        server
            .json(server.request(Method::DELETE, id, "/session"))
            .await;
        let session = server.wait_status(id, "/session", "terminated").await;
        assert_eq!(session["termination_reason"], "client_requested");
        server.wait_dead(&[vivado, child]).await;
        server.wait_status(id, "", "failed").await;
        let rejected = server
            .request(Method::PUT, Uuid::new_v4(), "")
            .json(&json!({"project": "forced", "reset_project": false}))
            .send()
            .await
            .unwrap();
        assert_eq!(rejected.status(), StatusCode::CONFLICT);
        assert_eq!(
            rejected.json::<Value>().await.unwrap()["error"]["code"],
            "project_reupload_required"
        );
        let reset = server.create("forced").await;
        server.upload_script(reset).await;
        let vivado = server.start(reset).await;
        server.complete(reset, &vivado).await;
    })
    .await;
}

#[tokio::test]
#[ignore = "requires Linux Vivado and pidfds; set VIVADO_PATH"]
async fn real_vivado_runtime_shutdown_terminates_tree() {
    run_scenario(|server| async move {
        let id = server.create("shutdown").await;
        server.upload_script(id).await;
        let vivado = server.start(id).await;
        let child = server.spawn_descendant(id, &vivado).await;
        server.runtime.shutdown().await;
        server.wait_dead(&[vivado, child]).await;
        let session = server.wait_status(id, "/session", "terminated").await;
        assert_eq!(session["termination_reason"], "service_shutdown");
    })
    .await;
}
